{% set version = "1.3-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatialeco
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatialEco_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatialEco/spatialEco_{{ version }}.tar.gz
  sha256: 9dfa427ee8b112446b582f6739a1c40a6e3ad3d050f522082a28ce47c675e57a

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base >=3.6
    - r-envstats
    - r-mass
    - r-rann
    - r-rcurl
    - r-spatialpack >=0.3
    - r-cluster
    - r-dplyr
    - r-exactextractr
    - r-maptools
    - r-mgcv
    - r-raster
    - r-readr
    - r-rgeos
    - r-rms
    - r-sf
    - r-sp
    - r-spatstat
    - r-spdep
    - r-yaimpute
  run:
    - r-base >=3.6
    - r-envstats
    - r-mass
    - r-rann
    - r-rcurl
    - r-spatialpack >=0.3
    - r-cluster
    - r-dplyr
    - r-exactextractr
    - r-maptools
    - r-mgcv
    - r-raster
    - r-readr
    - r-rgeos
    - r-rms
    - r-sf
    - r-sp
    - r-spatstat
    - r-spdep
    - r-yaimpute

test:
  commands:
    - $R -e "library('spatialEco')"           # [not win]
    - "\"%R%\" -e \"library('spatialEco')\""  # [win]

about:
  home: https://github.com/jeffreyevans/spatialEco
  license: GPL-3
  summary: Utilities to support spatial data manipulation, query, sampling and modelling. Functions include models for species population density, download utilities for climate and global deforestation spatial products, spatial smoothing, multivariate separability, point process model for creating pseudo- absences and sub-sampling,
    polygon and point-distance landscape metrics, auto-logistic model, sampling models, cluster optimization, statistical exploratory tools and raster-based metrics.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy

# Package: spatialEco
# Type: Package
# Title: Spatial Analysis and Modelling Utilities
# Version: 1.3-1
# Date: 2020-03-25
# Authors@R: c(person(family="Evans", given="Jeffrey S.", email = "jeffrey_evans@tnc.org", role = c("aut", "cre")))
# Description: Utilities to support spatial data manipulation, query, sampling and modelling. Functions include models for species population density, download utilities for climate and global deforestation spatial products, spatial smoothing, multivariate separability, point process model for creating pseudo- absences and sub-sampling, polygon and point-distance landscape metrics, auto-logistic model, sampling models, cluster optimization, statistical exploratory tools and raster-based metrics.
# Depends: R (>= 3.6.0)
# Imports: dplyr, exactextractr, sp, sf, raster, spatstat, cluster, spdep, readr, RCurl, rgeos, RANN, rms, yaImpute, SpatialPack (>= 0.3), MASS, mgcv, EnvStats, maptools, methods
# Maintainer: Jeffrey S. Evans <jeffrey_evans@tnc.org>
# License: GPL-3
# URL: https://github.com/jeffreyevans/spatialEco
# NeedsCompilation: no
# Repository: CRAN
# LazyData: true
# Encoding: UTF-8
# RoxygenNote: 7.1.0
# Packaged: 2020-03-25 23:43:59 UTC; jeffrey_evans
# Author: Jeffrey S. Evans [aut, cre]
# Date/Publication: 2020-04-01 14:00:03 UTC
